#version: "3.8"

services:
  flask:
    build: .
    container_name: gatorconfig-flask
    ports:
      - "5000:5000"
    networks:
      - gator-net
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  nginx:
    image: nginx:alpine
    container_name: gatorconfig-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - gator-net

networks:
  gator-net:
